wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 16
architecture:
  desc: null
  value: SSDwVGG
data:
  desc: null
  value: CellBinDB
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1738878471.3791
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.11.5
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
